### ISSUE TITLE
Login failed for user 'PerfTest'.  Reason: The password of the account has expired.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/EndToEnd#128]
Connection string contains username / password so the user seems to be expired on the SQL database.

```
System.InvalidOperationException: Could not create database. ---> System.Data.SqlClient.SqlException: Login failed for user 'PerfTest'.  Reason: The password of the account has expired.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at SqlHelper.ExecuteScript(String connectionString, String sql) in C:\BuildAgent\work\b8379f157f55efb1\src\PerformanceTests\Utils\SqlHelper.cs:line 18
   at SqlHelper.CreateDatabase(String connectionString) in C:\BuildAgent\work\b8379f157f55efb1\src\PerformanceTests\Utils\SqlHelper.cs:line 55
   --- End of inner exception stack trace ---
   at SqlHelper.CreateDatabase(String connectionString) in C:\BuildAgent\work\b8379f157f55efb1\src\PerformanceTests\Utils\SqlHelper.cs:line 60
   at SqlServerProfile.ISetup.Setup()
   at Host.Program.InvokeSetupImplementations(Permutation permutation) in C:\BuildAgent\work\b8379f157f55efb1\src\PerformanceTests\Common\Program.cs:line 71
   at Host.Program.Main() in C:\BuildAgent\work\b8379f157f55efb1\src\PerformanceTests\Common\Program.cs:line 38
```

Source: https://builds.particular.net/repository/download/PerfTests_DeployAndRun/166962:id/perftests/%40/Performance/SendThroughputFixture/ForRunner/SQLServer~Large~/trace.log

**Comment by gbiellem** [comment]
@ramonsmits VM updated and user should no longer have an expiry.
