### ISSUE TITLE
Verify SQL connection strings on Azure env for large Connection Timeout value

### ISSUE THREAD

**Issue by ramonsmits** [Particular/EndToEnd#230]
If the max connection pool size is less or very equal to the allowed max concurrency level issues can occur. Tasks could wait indefinitely for a new connection if the connection pool is depleted. If the connection strings are configured with a very high Connection Timeout value (like Azure SQL default 300 seconds) it will appear if the whole process is stalled/locked and it will take a very long time until the following exception occurs:

```
2016-10-02 18:50:16.2444|WARN|28|NServiceBus.Transport.SQLServer.MessagePump|Sql receive operation failed
System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<>c__DisplayClass2_0.<<Default>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<OpenNewConnection>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ReceiveWithNativeTransaction.<ReceiveMessage>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.MessagePump.<InnerReceive>d__6.MoveNext()
```

Need to verify it the Connection Timeout is low on the Azure perftest environment as keeping this value low will make sure transactions are not unnecesarrily too long due to the pool being empty and this also makes sure resources will quickly be released again and then retried.

**Comment by ramonsmits** [comment]
Connection string values for SQL Azure has a connection time out of 300 which is now reduced to 10 seconds.
